### ISSUE TITLE
Folder Not Found

### ISSUE THREAD

**Issue by nabsiddiqui** [rafaqz/citation.vim#5]
I continue to have similar problems to #1 #2 perhaps due to #4.  I get a message stating:

```
[unite.vim] function unite#action#do[70]..244[1]..unite#start_t
emporary[1]..unite#start#temporary[59]..unite#start#standard[50
]..unite#candidates#_recache[74]..<SNR>131_recache_candidates_l
oop[42]..<SNR>131_get_source_candidates[40]..177[1]..<SNR>128_m
ap_entries[1]..<SNR>128_get_source, line 9
[unite.vim] Vim(let):Traceback (most recent call last):
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is citation/author
```
Running test.py yields

```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    items = builder.build_list()
  File "/home/nabeel/.vim/plugged/citation.vim/python/citation_vim/../citation_vim/citation.py", line 71, in build_list
    for item in self.get_items():
  File "/home/nabeel/.vim/plugged/citation.vim/python/citation_vim/../citation_vim/citation.py", line 92, in get_items
    parser = self.get_parser()
  File "/home/nabeel/.vim/plugged/citation.vim/python/citation_vim/../citation_vim/citation.py", line 113, in get_parser
    parser = bibtexParser(self.context)
  File "/home/nabeel/.vim/plugged/citation.vim/python/citation_vim/../citation_vim/bibtex/parser.py", line 13, in __init__
    self.et_al_limit = context.et_al_limit
AttributeError: 'Context' object has no attribute 'et_al_limit'
```
The following are the relevant sections of my vimrc:
```
let g:citation_vim_mode="bibtex"
let g:citation_vim_bibtex_file="/home/nabeel/Dropbox/Miscellaneous/Zotero/library.bib"
let g:citation_vim_cache_path="/home/nabeel/.vim/citations/"
let g:citation_vim_outer_prefix="["
let g:citation_vim_inner_prefix="@"
let g:citation_vim_suffix="]"
let g:citation_vim_et_al_limit=2
```

**Comment by rafaqz** [comment]
Apologies that test needs updating after the last pull requst, wich might
have caused your issue too... But unites 'gather candidates' error could be
anything. I'll have a look in the next few days.

**Comment by nabsiddiqui** [comment]
No problem.  Thanks for the quick reply.  Perhaps it is something related to Ubuntu or python3.

**Comment by rafaqz** [comment]
I fixed the test file and simplified a little, instructions are in the readme now. Bibtex is working fine for me so it may be your particular setup or bibtex file but post the test output and I'll look into it.

**Comment by nabsiddiqui** [comment]
This may be something small but this is what I get running the test:

'''
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    context.source = citation
NameError: name 'citation' is not defined
'''

**Comment by rafaqz** [comment]
Sorry bugfixing on the road was a bad idea. Should be ok now.

**Comment by DancingQuanta** [comment]
The tests are okay for me (I am on cygwin) but get similar errors at `gather_candidates`.
When I tried `:Unite citation/author` I get
```
[unite.vim] function <SNR>30_call_unite[33]..unite#start[1]..unite#start#standard[50]..unite#candidates#_recache[74]..<SNR
>68_recache_candidates_loop[42]..<SNR>68_get_source_candidates[40]..20[1]..<SNR>65_map_entries[1]..<SNR>65_get_source, lin
e 11
[unite.vim] Vim(let):Traceback (most recent call last):
[unite.vim] Error occurred in gather_candidates!
```
Using `vim -V9log` got bit more detail
```
line 2: sourcing "/cygdrive/c/Users/andre/.vim/dein/.cache/.vimrc/.dein/autoload/vital/_unite/Data/String.vim"
finished sourcing /cygdrive/c/Users/andre/.vim/dein/.cache/.vimrc/.dein/autoload/vital/_unite/Data/String.vim
continuing in function <SNR>30_call_unite[33]..unite#start[1]..unite#start#standard[50]..unite#candidates#_recache[74     ]..<SNR>93_recache_candidates_loop[3]..unite#util#strchars[1]..<SNR>82_get_string[2]..<SNR>83_import[11]..<SNR>83__im     port[4]..<SNR>83__get_module
                                                                                                                                                                                                                                                                                 [unite.vim] function <SNR>30_call_unite[33]..unite#start[1]..unite#start#standard[50]..un     ite#candidates#_recache[74]..<SNR>93_recache_candidates_loop[42]..<SNR>93_get_source_candidates[40]..20[1]..<SNR>90_m     ap_entries[1]..<SNR>90_get_source, line 11
[unite.vim] Vim(let):Traceback (most recent call last):
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is citation/author
Executing FuncUndefined Auto commands for "*"
autocommand call dein#autoload#_on_func(expand('<afile>'))

```

**Comment by rafaqz** [comment]
DancingQuanta - if the tests work but vim is still breaking it normally means a font encoding problem, also likely with cygwin. Probably the zotero database is in a different encoding to what vim is trying to print, or my code is buggy with font encoding, which is a nightmare in python and I'm admittedly not well across. Try using bibtex for now as it's a lot less complicated than zotero and shouldn't have the encoding problems, where a lot of things can break accross platforms/font encoding/zotero/better-bibtex versions.

**Comment by DancingQuanta** [comment]
Trying a bib file with one bib entry didn't really help. I did notice for some citation source etc file gives me empty buffer error after gather candidate error.
Any pointers? I can write in python as well

**Comment by rafaqz** [comment]
You should get better error messages in the latest version, try it and paste the results
