### ISSUE TITLE
Problem: error when using latest version with zotero

### ISSUE THREAD

**Issue by sappo** [rafaqz/citation.vim#6]
I get the following error when I call the unite source:
```
Citation.vim error:
Traceback (most recent call last):
  File "/home/sappo/.vim/bundle/citation.vim/python/citation_vim/citation.py", line 22, in connect
    return Builder(Loader().context).build_source()
  File "/home/sappo/.vim/bundle/citation.vim/autoload/unite/sources/../../../python/citation_vim/builder.py", line 25, in build_source
    description = self.describe(item)
File "/home/sappo/.vim/bundle/citation.vim/autoload/unite/sources/../../../python/citation_vim/builder.py", line 111, in describe
    return self.describe_with_source_field(description_values, item)
  File "/home/sappo/.vim/bundle/citation.vim/autoload/unite/sources/../../../python/citation_vim/builder.py", line 138, in describe_with_source_field
    return description_format.format(*description_values)
KeyError: 'type'
[unite.vim] function unite#helper#call_unite[33]..unite#start[1]..unite#start#standard[50]..unite#candidates#_recache[74]..<SNR>168_recache_candidates_loop[42]..<SNR>168_get_source_candidates[40]..141, line 3
[unite.vim] Vim(return):E712: Argument of map() must be a List or Dictionary
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is citation/key
```

**Comment by rafaqz** [comment]
Fixed.
