### ISSUE TITLE
Problem: citation crashes with zotero

### ISSUE THREAD

**Issue by sappo** [rafaqz/citation.vim#8]
Hi @rafaqz,

I still get an error when I try to use the latest version of citation.vim with zotero:
```
Citation.vim error:
Traceback (most recent call last):
  File "/home/sappo/.vim/bundle/citation.vim/python/citation_vim/citation.py", line 22, in connect
    return Builder(Loader().context).build_source()
  File "/home/sappo/.vim/bundle/citation.vim/autoload/unite/sources/../../../python/citation_vim/builder.py", line 25, in build_source
    description = self.describe(item)
  File "/home/sappo/.vim/bundle/citation.vim/autoload/unite/sources/../../../python/citation_vim/builder.py", line 111, in describe
    return self.describe_with_source_field(description_values, item)
  File "/home/sappo/.vim/bundle/citation.vim/autoload/unite/sources/../../../python/citation_vim/builder.py", line 141, in describe_with_source_field
    return description_format.format(*description_values)
KeyError: 'type'
[unite.vim] function unite#helper#call_unite[33]..unite#start[1]..unite#start#standard[50]..unite#candidates#_recache[74]..<SNR>294_recache_candidates_loop[42]..<SNR>294_get_source_candidates[40]..592, line 3
[unite.vim] Vim(return):E712: Argument of map() must be a List or Dictionary
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is citation/key
```

**Comment by rafaqz** [comment]
Ok try that. I let something slip through into the vim defaults that get overridden in my setup, and cant be covered in a test. If it's still broken paste your vimrc.

**Comment by sappo** [comment]
The error still exists. Here are my settings:
```vim
if isdirectory($ZOTERO_HOME)
      let g:citation_vim_mode='zotero'
      let g:citation_vim_zotero_path=$ZOTERO_HOME
      "let g:citation_vim_collection='Master_Thesis'
    else
      let g:citation_vim_mode='bibtex'
      let g:citation_vim_bibtex_file=globpath('.', '*.bib')
    endif
    let g:citation_vim_et_al_limit=2
    " Create citation cache dir if necessary
    if !isdirectory($HOME . '/.vim/citation')
      silent !mkdir -p ~/.vim/citation >/dev/null 2>&1
    endif
    let g:citation_vim_cache_path='~/.vim/citation'
    " Pandoc citation style
    let g:citation_vim_outer_prefix='['
    let g:citation_vim_inner_prefix='@'
    let g:citation_vim_suffix=']'
```

**Comment by rafaqz** [comment]
Ok it was just me doing something dumb nothing to do with your setup. Should work now.

**Comment by sappo** [comment]
It does! Thanks!
